### ISSUE TITLE
Firestore 데이터 모델링 (수정 필요)

### ISSUE THREAD

**Issue by loopbackseal** [Rob-Yoo/ApusCheckIn_Team1#10]
- [x] 현재는 `hadCheckedIn`과 `intraID` 두개로만 진행하고 있는데, `hadCheckedIn` 대신에 `Date`를 Array 형태로 받도록 수정!
- [x] 이미 출석 체크가 된 경우, 해당 일자의 데이터를 갱신하지 않도록 수정!

**Comment by triplecheeseburger** [comment]
둘다 클로즈해주삼
